name = "cardpress-refresh"
main = "worker/cardpress-api.js"
compatibility_date = "2024-04-27"

[[d1_databases]]
binding = "DB"
database_name = "cardpress-blog"
database_id = "your-d1-database-id"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cardpress-storage"

[vars]
ADMIN_EMAIL = "admin@example.com"
APP_ID = "cardpress-blog"

[env.production.vars]
ADMIN_EMAIL = "admin@example.com"
APP_ID = "cardpress-blog"
