name = "cardpress-refresh"
main = "worker/cardpress-api.js"
compatibility_date = "2024-04-27"

[[d1_databases]]
binding = "DB"
database_name = "cardpress-blog"
database_id = "08fd85c0-cada-48ab-b651-9009d90b56cb"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cardpress-storage"

[vars]
ADMIN_EMAIL = "me@jon.io"
APP_ID = "cardpress-blog"
GITHUB_REPO = "HeyFireHQ/ticker-blog"
GITHUB_DEPLOY_BRANCH = "content"

[env.production.vars]
ADMIN_EMAIL = "me@jon.io"
APP_ID = "cardpress-blog"
GITHUB_REPO = "HeyFireHQ/ticker-blog"
GITHUB_DEPLOY_BRANCH = "content"

# Note: Add these secrets via Wrangler CLI:
# wrangler secret put GITHUB_TOKEN
# wrangler secret put DEPLOY_WEBHOOK_URL
# wrangler secret put REFRESH_SECRET_KEY
# wrangler secret put DEPLOY_HOOK_URL
