name: Build and Deploy CardPress Blog

on:
  workflow_dispatch:   # manual trigger
  repository_dispatch: # for external webhook triggers (like Trello or your own server)

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Build CardPress blog
        run: python generate.py

      - name: Commit and Push output to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git checkout --orphan output-branch
          git rm -rf .
          cp -r output/* .
          git add .
          git commit -m "Deploy generated site"
          git push --force origin output-branch
